### ISSUE TITLE
Discosgs to MusicBrainz script fails to import all the tracks

### ISSUE THREAD

**Issue by gczobel** [murdos/musicbrainz-userscripts#101]
Trying to import the below release from Discosgs found that not all the tracks are imported (only 6 of 41)

https://www.discogs.com/Pergolesi-Scarlatti-Bononcini-St-Johns-College-Choir-George-Guest-2-Sch%C3%BCtz-Choir-Roger-Norrington-S/release/7468379

**Comment by zas** [comment]
This release has sub tracks, which aren't supported yet in MusicBrainz.

Import script concatenates subtrack titles, so its tracklist matches the actual CD tracklist (counting only tracks, not subtracks):

CD 1 with 2 tracks (41:15 + 32:05)
CD 2 with 6 tracks

For example, on Discogs, track 3 on CD 2 is listed as:

2-3 	I Magnificat (Chorus) 	2:51
2-4 	II Et Misericordia (Soprano, Contralto) 	1:44
2-5 	III Deposuit Potentes (Chorus) 	1:48
2-6 	IV Suscepit Israel (Tenor, Bass) 	1:51
2-7 	V Sicut Locutus Est — Gloria (Chorus) 	3:39

On MB:
Magnificat In C Major: I Magnificat (Chorus) / II Et Misericordia (Soprano, Contralto) / III Deposuit Potentes (Chorus) / IV Suscepit Israel (Tenor, Bass) / V Sicut Locutus Est — Gloria (Chorus) 11:53


So i think the script is doing its best here, which such complex tracklist.
Note: if you have CD in hands, you can check discid and verify how many actual tracks are on CDs.

**Comment by gczobel** [comment]
I see... there are not really subtracks... There are 41 tracks on 2 CDs... I think they tried to use (wrongly) the subtrack to separate different works.
Thanks for the fast answer... I think you can close the issue.
