### ISSUE TITLE
Idea: Spotify import script

### ISSUE THREAD

**Issue by liftarn** [murdos/musicbrainz-userscripts#108]
Since the Spotify catalogue is also accessible via the website it would be nice to have an importer for that as well. Most will probably be on iTunes as well, but not everything.

**Comment by jesus2099** [comment]
When I look at a [Spotify album page](https://open.spotify.com/album/2w1YJXWMIco6EBf0CovvVN) it shows floored track lengths.
If someone makes an importer, it should take its data from the [Spotify album API](https://api.spotify.com/v1/albums/2w1YJXWMIco6EBf0CovvVN) that provides `duration_ms` that can then be more properly rounded.

1. BLACKSTAR / duration_ms: 597933 → 597.933 → 9:57.933 ≈ **9:<ins>58</ins>**
2. ’TIS A PITY SHE WAS A WHORE (explicit) / duration_ms: 292626 → 292.626 → 4:52.626 ≈ **4:<ins>53</ins>**
3. LAZARUS / duration_ms: 382386 → 382.386 → 6:22.386 ≈ 6:22
4. SUE (or IN A SEASON OF CRIME) / duration_ms: 280373 → 280.373 → 4:40.373 ≈ 4:40
5. GIRL LOVES ME (explicit) / duration_ms: 291946 → 291.946 → 4:51.946 ≈ **4:<ins>52</ins>**
6. DOLLAR DAYS / duration_ms: 284813 → 284.813 → 4:44.813 ≈ **4:<ins>45</ins>**
7. I CAN’T GIVE EVERYTHING AWAY / duration_ms: 347280 → 347.280 → 5:47.280 ≈ 5:47

Maybe we could set explicit in the recording comments, it could ease future so called explicit and clean editions.

**Comment by liftarn** [comment]
Some interesting things being discussed at https://community.metabrainz.org/t/musicbrainz-picard-interaction-with-spotify/210717/13

**Comment by Jormangeud** [comment]
Here is a script for Spotify: #209

**Comment by Freso** [comment]
Going to close this. :) There are a couple of scripts floating around for this, but above all of those I’d recommend people wanting to import from Spotify to use a-tisket: https://community.metabrainz.org/t/a-multi-source-seeder-for-digital-releases/444000?u=freso

Others may disagree, in which case you’re welcome to re-open this, but this is my opinion, and I’m WP:BB’ing it. ;)
