### ISSUE TITLE
Release Group image moved

### ISSUE THREAD

**Issue by CyberSkull** [murdos/musicbrainz-userscripts#115]
The Release Group image has been moved on the MB server. https://musicbrainz.org/static/images/entity/release_group.png returns a 404 error.

**Comment by murdos** [comment]
https://musicbrainz.org/static/images/entity/release_group.svg should be used instead. What is the script that uses this URL?

**Comment by CyberSkull** [comment]
The Discogs script. It last updated for me on the 21st.
