### ISSUE TITLE
Beatport Scripts: Not working - wrong include/exclude URLs in script settings?

### ISSUE THREAD

**Issue by brianroach** [murdos/musicbrainz-userscripts#125]
They are no longer using pro.beatport.com & are now re-directing everyone to the original beatport.com.
## Most importantly
- the URL http://beatport.com/release is incorrect. It should be http://beatport.com/releases for both Beatport plugins (notice the 's' to make it plural)

**Edit:** They do appear to be using the singular version of the URL as can be seen here, but it it still not working: https://www.beatport.com/release/funkiss-ep/1695074

**Comment by VxJasonxV** [comment]
`/releases` is the landing page for browsing releases, the relevant URLs it needs to act on are still `/release/*`. This is the reason why I implemented it as a new script, so I can just nuke the original `beatport_importer.user.js` and use the `beatport_pro_importer.user.js` file's contents instead.

Cursory testing looks good to me, I'll run a few more checks during the daytime and submit a PR to do exactly what I said above if all still looks good.

**Comment by brianroach** [comment]
Were you able to get this working? Are you using Tampermonkey by chance?
