### ISSUE TITLE
Bandcamp import: unrelated edit note

### ISSUE THREAD

**Issue by jesus2099** [murdos/musicbrainz-userscripts#134]
http://musicbrainz.org/edit/42761008 says « imported from some bandcamp » but is editing another release.

**Comment by zas** [comment]
I don't think it is an issue with the importer, the edit is a Add cover art edit, which doesn't come from the importer for sure.

@murdos: why do you think it is a bug ?
@jesus2099: imho the editor copied the edit note manually, and yes, it is unrelated to the release but that's not a bug in the Bandcamp importer either.

**Comment by jesus2099** [comment]
Thanks @zas, I thought the importer could upload to CAA (it would be complex but a killer feature).
I think you may close this issue, @murdos.  :)

**Comment by jesus2099** [comment]
Indeed, judging from [the source code](https://github.com/murdos/musicbrainz-userscripts/blob/044037ab498445ec0a6f2142777adf11f0ed60b4/bandcamp_importer.user.js#L294-L300), this script does not seem to queue **Add Cover Art** edits. :)
