### ISSUE TITLE
discogs importer: problem with disambiguated artists

### ISSUE THREAD

**Issue by bsammon** [murdos/musicbrainz-userscripts#135]
https://musicbrainz.org/edit/42815683
For track 7 of this edit, the discogs source links to [The Barons (8)](https://www.discogs.com/artist/1341581-The-Barons-8)
And [The Barons (60s Dallas/Forth Worth garage rock band)](https://musicbrainz.org/artist/f49467b2-4b36-47aa-9c06-7d47c93fdd86) on Musicbrainz is linked to "The Barons (8)"
but for some reason, this edit incorrectly has [The Barons (Orlando, Florida garage rock)](https://musicbrainz.org/artist/0217d6cd-6e2e-4edb-897f-b3b31d3b9990) on track 7.

**Comment by zas** [comment]
This isn't a problem with the Discogs Importer, the editor still have to associate tracks to correct artist.

**Comment by bsammon** [comment]
Oh...the discogs importer doesn't (attempt to) detect when there's a musicbrainz artist with a link to the discogs artist?
Well... I suppose you could change this to a feature request then, if you wanted to.

**Comment by bsammon** [comment]
Hmm... or maybe github doesn't have a "feature request" thingy.
