### ISSUE TITLE
Display shortcut for relationships on MusicBrainz: does not work for multipage lists

### ISSUE THREAD

**Issue by SothoTalKer** [murdos/musicbrainz-userscripts#136]
When browsing entities that have more than 100 entries, those are split up.

On the first view, relationships are displayed correctly:
https://musicbrainz.org/label/672a919c-9050-479a-827c-5570deeaa0c3

If going to page 2, 3, or back to page 1, this script does not show relationships anymore:
https://musicbrainz.org/label/672a919c-9050-479a-827c-5570deeaa0c3?page=1

The reason is probably the appended "?page= ".

**Comment by zas** [comment]
To which userscript is this related ?

**Comment by SothoTalKer** [comment]
https://github.com/murdos/musicbrainz-userscripts/blob/master/mb_relationship_shortcuts.user.js
