### ISSUE TITLE
Discogs importer doesn't handle multiple country combinations

### ISSUE THREAD

**Issue by CyberSkull** [murdos/musicbrainz-userscripts#143]
https://www.discogs.com/Various-Guitar-Art-Festival-Belgrade-Live-2006/release/7938650
The release country is "Serbia and Montenegro" and the importer just leaves it blank. For cases with a joining phrase like "and", "," or "&" in the country it should split the string on those and try each country individually. The ideal behavior here would be that the country string is parsed and "2006 Serbia" and "2006 Montenegro" is filled in on the MB page.

**Comment by murdos** [comment]
I tested the import of this Discogs release, and it's automatically attributed to country "Serbia and Montenegro" in MB, so it seems to work now.
Closing the ticket, feel free to reopen if you have another example.
