### ISSUE TITLE
Discogs importer: Artist search fails when artist name contains "&"

### ISSUE THREAD

**Issue by SothoTalKer** [murdos/musicbrainz-userscripts#148]
As seen in this example:
https://www.discogs.com/AP-Project-Feat-Zemya-Hamilton-Sunrize/release/492857

The first artist is not yet linked to a MB entity, so you can search if that artist already exists at all.
The name contains a "&", so the search then only searches for artist "A", not for "A&P Project", since the "&" is not escaped properly:
https://beta.musicbrainz.org/search?query=A&P%20Project&type=artist&indexed=1

**Comment by SothoTalKer** [comment]
A quick solution is to convert the "&" to "%26", if that is possible in the script.

**Comment by zas** [comment]
On https://www.discogs.com/AP-Project-Feat-Zemya-Hamilton-Sunrize/release/492857 "A&P Project" is properly linked to https://musicbrainz.org/artist/b80ee1c4-ed95-44cf-81de-8c1d2181c57c for me
Do you still have the issue with the current version ?

**Comment by murdos** [comment]
The issue can't be reproduced, so I'm closing it.
