### ISSUE TITLE
Discogs Object not being parsed correctly for "format"

### ISSUE THREAD

**Issue by halfacandan** [murdos/musicbrainz-userscripts#15]
Hi

This discogs release was not offering an import button: http://www.discogs.com/release/5460755

I found a work-around (not very good but it flags up the problem). I traced the error to one line of code in the parseDiscogsRelease function:

        // Create release if needed
        if ( !release.discs[releaseNumber-1] ) {
            release.discs.push(new Object());
            release.discs[releaseNumber-1].tracks = [];
            // Halfacandan Commented out - release.discs[releaseNumber-1].format = release_formats[releaseNumber-1];
			// Halfacandan Changes Start
			if(typeof release_formats[releaseNumber-1] === "undefined") {
				if(typeof release.discs[releaseNumber-1].tracks.format === "undefined") {			
					release.discs[releaseNumber-1].format = "CD";
				} else {
					release.discs[releaseNumber-1].format = release.discs[releaseNumber-1].tracks.format;
				}
			} else {
				release.discs[releaseNumber-1].format = release_formats[releaseNumber-1];
			}
			// Halfacandan Changes End
        }

**Comment by zas** [comment]
Fixed among others by https://github.com/murdos/musicbrainz-userscripts/commit/1bf80fbaf918e12028d89e1f3801298f63e65977
