### ISSUE TITLE
Discogs script doesn't work for me on some URLS

### ISSUE THREAD

**Issue by mll0** [murdos/musicbrainz-userscripts#151]
Well, the title says it all. I hadn't used the userscript for  a couple of months maybe, and today, when I try to import https://www.discogs.com/fr/Mickey-3D-La-Tr%C3%AAve/master/625080 or https://www.discogs.com/en/master/625080 (or any other release of this release group), the beloved "Import into MB" is missing (and also the whole Musicbrainz section).

While, when I go to the test URL https://www.discogs.com/fr/fr/release/1566223 provided within the script, the script is working.

And after a couple of browsing, I could reach the URL https://www.discogs.com/fr/Mickey-3D-La-Tr%C3%AAve/release/1491544, wich works.

**Comment by VxJasonxV** [comment]
You have to be on a specific /release/ and not the /master/, because releases have relevant metadata (date, region, medium) that the master doesn't.

**Comment by mll0** [comment]
OK, I didn(t know that. Thanks for the information.
