### ISSUE TITLE
FMA userscript not working with Chromium + Tampermonkey

### ISSUE THREAD

**Issue by stragu** [murdos/musicbrainz-userscripts#152]
I am using the FMA import script with Chromium 59.0.3071.109 with Tampermonkey 4.3.6, and I see no buttons added to FMA release pages.

How can I troubleshoot?

**Comment by madmouser1** [comment]
@stragu I'll have a look

**Comment by madmouser1** [comment]
@stragu please test this version: https://github.com/madmouser1/musicbrainz-userscripts#fma_importer
if it works I will push the change to this repository.
I have tested it with Firefox 58 & Tampermonkey 4.5

**Comment by stragu** [comment]
Super, yes, it works as expected now (with Chromium 64.0.3282.119 and Tampermonkey 4.5).
Thanks for that! What was the fix?
