### ISSUE TITLE
Bandcamp script: Free streaming link added to non-streemable releases

### ISSUE THREAD

**Issue by culinko** [murdos/musicbrainz-userscripts#157]
Free streaming links are still added to Bandcamp releases which can't be streamed for free. Example release: http://music.monstercat.com/track/bubbles (it's already added to mb). Thanks for the fix!

**Comment by zas** [comment]
@culinko : test if https://github.com/murdos/musicbrainz-userscripts/pull/178 works for you

**Comment by culinko** [comment]
Thanks a lot! Works perfectly (tested my example link).
