### ISSUE TITLE
Qobuz import script not working (anymore)

### ISSUE THREAD

**Issue by fuschl** [murdos/musicbrainz-userscripts#164]
The button for import to MusicBrainz does not appear with the following set-up:
Script version: 2016.05.29.0
Example URL: https://www.qobuz.com/de-de/album/spirit-on-a-mission-michael-schenkers-temple-of-rock/0884463706392
Add-On software: Tampermonkey
Browser: FF 57.0.3

**Comment by zas** [comment]
It works now (re-open if not)
