### ISSUE TITLE
Trinidad & Tobago from Discogs does not select country

### ISSUE THREAD

**Issue by CyberSkull** [murdos/musicbrainz-userscripts#166]
The Discogs importer does not select any country when "Trinidad & Tobago" is the country on Discogs. The country is spelled "Trinidad and Tobago" on MusicBrainz, so that may be the problem.

**Comment by murdos** [comment]
Try to change the string here: https://github.com/murdos/musicbrainz-userscripts/blob/master/discogs_importer.user.js#L1006
If it works, could you please submit a patch?

**Comment by liftarn** [comment]
I also noticed several other countries like USSR/Soviet Union, Yugoslavia, Serbia and Montenegro, Bosnia & Herzegovina...
