### ISSUE TITLE
Discogs importer doesn't show up on Firefox

### ISSUE THREAD

**Issue by ewauq** [murdos/musicbrainz-userscripts#168]
Since a recent Firefox update, the Discogs importer doesn't seem to work anymore. 
On Chrome everything is ok.

There is no error on the FF console. The version used on both browsers is 2017.02.25.0.

![image](https://user-images.githubusercontent.com/1007507/34605251-2cb73eec-f20b-11e7-93ff-2f3a8a47e036.png)
  
![image](https://user-images.githubusercontent.com/1007507/34605395-bdf6ff0a-f20b-11e7-9211-e3c1eb69f9fa.png)

**Comment by murdos** [comment]
Probably related to #159

**Comment by thefinalwolf** [comment]
I'm having a similar issue with the buttons showing up in Firefox (and Chrome).

Firefox console shows:

> Source map error: Error: NetworkError when attempting to fetch resource.
> Resource URL: moz-extension://\<UID\>/%20Import%20Discogs%20releases%20to%20MusicBrainz.user.js#15
> Source Map URL: jquery.min.map

Same thing with the Bandcamp script:
> Source map error: Error: NetworkError when attempting to fetch resource.
> Resource URL: moz-extension://\<UID\>/%20Import%20Bandcamp%20releases%20to%20MusicBrainz.user.js#16
> Source Map URL: jquery.min.map


I also launched a clean Windows Sandbox with Chrome installed and had similar source map errors.
It didn't matter what extension was used (tried Violentmonkey and Tampermonkey).

Might have something to do with stuff I found while looking around:

> - https://github.com/webpack/webpack/issues/1194

Possible workaround I haven't tried yet:
>   https://github.com/webpack/webpack/issues/1194#issuecomment-402494524

Core issue seems to lead all the way back to:
>   https://bugzilla.mozilla.org/show_bug.cgi?id=1437937

**Comment by kellnerd** [comment]
@thefinalwolf Discogs changed the layout of their release pages ago, maybe this caused your problem:
- Issue: #411
- Fix: #412

**Comment by thefinalwolf** [comment]
@kellnerd It's possible; I'm not familiar with JavaScript and have only created a few for sites that bugged me.
I don't see errors specific to not being able to find elements though.

I'll try a few tests once I can allocate time.

**Comment by kellnerd** [comment]
@thefinalwolf You don't need to have a look at the code changes, all I wanted to say that your problem might not be the one in this issue but the other one which has already been fixed. So you would only need to update the userscript and see if the import button shows up again.

**Comment by thefinalwolf** [comment]
@kellnerd Ah, I see.
Yup, replacing the script with the one from #412 worked just fine. 
Same network error, but doesn't matter since I could still import.

Thanks for pointing this out.
I wonder why this fix hasn't been merged into the main branch.

**Comment by thefinalwolf** [comment]
Never mind, it was a recent commit I didn't notice 7 days ago.
Sweet.

**Comment by kellnerd** [comment]
Six year old ticket, no longer actionable. Please file a new issue for problems with the latest userscript version if necessary.
