### ISSUE TITLE
Musicbrainz DiscIds Detector breaks pages on red

### ISSUE THREAD

**Issue by 5moufl** [murdos/musicbrainz-userscripts#182]
The script breaks onclick events on torrent pages and doesn’t seem to work anymore. No discIDs are displayed when a log is available.

**Comment by 5moufl** [comment]
discIDs are back but the onclick events are still broken.

**Comment by murdos** [comment]
Can you tell what browser and userscript engine you're using?
I've no problem with Firefox+Tampermonkey.

**Comment by 5moufl** [comment]
Firefox 60.0.1 with ViolentMonkey 2.9.4

**Comment by murdos** [comment]
It seems to be related to ViolentMonkey, that doesn't sandbox the injection of jQuery, that then conflicts with the jQuery of the gazelle site (same issue on APL).
I'm afraid there's nothing I can do. Can you use TamperMonkey instead?

**Comment by 5moufl** [comment]
I’ll do that or switch back to GreaseMonkey at some point. I don’t need the script enabled at all times, I can also enable it when needed with VM.
Thanks for the help.
