### ISSUE TITLE
Last.fm script not showing

### ISSUE THREAD

**Issue by pdupreez** [murdos/musicbrainz-userscripts#187]
The import button does not show up on the Last.fm page. Using Vivaldi and Chrome

**Comment by liftarn** [comment]
As there no longer is any music on Last.fm you shouldn't do imports from there.

**Comment by pdupreez** [comment]
Ah, ok. Thanks

**Comment by murdos** [comment]
@liftarn does that mean we should remove the Last.fm importer?

**Comment by liftarn** [comment]
Yes, there is no point in having it now.

**Comment by murdos** [comment]
Lastfm importer removed with #199 => I'm closing this issue
