### ISSUE TITLE
Batch-add "performance of" relationships should add an edit note

### ISSUE THREAD

**Issue by jesus2099** [murdos/musicbrainz-userscripts#189]
https://musicbrainz.org/edit/49586656#note-49586656-6
These edits should allow edit note by the editor (I don’t know if it already does) but should anyway always add an edit note footer saying that this edit was created by **Batch-add "performance of" relationships** so it could hint the future editors of the relatively poor trust value of those global/broad slightly blind edits, compared with manual edit, based on a specific release.

**Comment by psychoadept** [comment]
Second this, there needs to be an edit note
