### ISSUE TITLE
Qobuz import not working?

### ISSUE THREAD

**Issue by smoothquark** [murdos/musicbrainz-userscripts#191]
Just installed the qobuz script. I do not get the import button. Error on console seems to indicate that there is a problem with the app id:

https://www.qobuz.com/api.json/0.2/album/get?album_id=uek8tmqrxyatb&app_id=667867760

{"status":"error","code":400,"message":"Invalid or missing app_id parameter"}

**Comment by roman412** [comment]
confirm on this
