### ISSUE TITLE
Qobuz import script not working (Chrome)

### ISSUE THREAD

**Issue by fuschl** [murdos/musicbrainz-userscripts#203]
The button for import to MusicBrainz does not appear with the following set-up:
Script version: 2018.11.23.1
Example URL: https://www.qobuz.com/de-de/album/premonitions-the-charisma-recordings-1975-1983-steve-hackett/0060254743050
Add-On software: Tampermonkey
Browser: Chrome 71.0.3578.98

Error in console:
Uncaught TypeError: Cannot read property 'responseURL' of undefined

**Comment by Jormangeud** [comment]
My bad. Fix in the PR.
