### ISSUE TITLE
Discogs importer: medium mapping for lathe cut

### ISSUE THREAD

**Issue by liftarn** [murdos/musicbrainz-userscripts#215]
Discogs have the format https://www.discogs.com/search/?format_exact=Lathe+Cut but it don't exist in MusicBrainz yat so perhaps it should map to phonograph record.

**Comment by liftarn** [comment]
Fixed in https://github.com/murdos/musicbrainz-userscripts/pull/216

**Comment by zas** [comment]
@murdos, @liftarn: please update version so auto upgrades can happen ;)
