### ISSUE TITLE
Qobuz importer do not show buttons anymore

### ISSUE THREAD

**Issue by zas** [murdos/musicbrainz-userscripts#217]
Firefox 65.0.1 linux

The js interceptor at https://github.com/murdos/musicbrainz-userscripts/blob/master/qobuz_importer.user.js#L305 doesn't look to work anymore.

**Comment by Jormangeud** [comment]
That should fix the race condition.
Works here with the patch on Tampermonkey and fx 66.0.1 on linux.

**Comment by zas** [comment]
Yup, the patch fixes it, thanks :+1:
