### ISSUE TITLE
Discogs Memory Stick should be imported as USB Flash Drive

### ISSUE THREAD

**Issue by jesus2099** [murdos/musicbrainz-userscripts#220]
[This release](https://musicbrainz.org/edit/60615348) where a [Memory Stick](https://www.discogs.com/release/12679820) was imported as **Other** instead of as [USB Flash Drive](https://musicbrainz.org/edit/60619278).

**Comment by liftarn** [comment]
Fixed it in https://github.com/murdos/musicbrainz-userscripts/pull/221
