### ISSUE TITLE
Discogs Digipak imported as Jewel Case

### ISSUE THREAD

**Issue by jesus2099** [murdos/musicbrainz-userscripts#227]
https://musicbrainz.org/edit/60842725

**Comment by liftarn** [comment]
Could be because the text says "digipack" instead of "digipak".

**Comment by jesus2099** [comment]
Oh you’re right.
https://github.com/murdos/musicbrainz-userscripts/blob/be66a4520db260f24ddcefefaf08f64d3ff0aee7/discogs_importer.user.js#L571

**Comment by jesus2099** [comment]
It shouldn’t default to jewel case in any way.

**Comment by jesus2099** [comment]
I don't know this script bug I will test and propose a PR, I think, if there really is a bad package assign.

**Comment by liftarn** [comment]
Should be easy to add a line
else if (freetext.match(/digipack/)) release.packaging = 'digipak';

**Comment by jesus2099** [comment]
If this is the problem, even `freetext.match(/digipak/)` → `freetext.match(/digipac?k/)` but I don’t know if this is the (main) problem.
It should not default to jewel case but to _not set_. :)
I will check, thanks.

**Comment by jesus2099** [comment]
Thanks for spotting the *digipack*, @liftarn.
For this I have made a very small PR #229.

I close this ticket as there is no such bug, no fallback to jewel case when unknown package.
This release was imported with empty package and the editor must have erroneously selected jewel case manually, unfortunately..
