### ISSUE TITLE
Button to import from Discogs to MusicBrainz  missing

### ISSUE THREAD

**Issue by lvbaal** [murdos/musicbrainz-userscripts#233]
I used to import albums from Discogs to MusicBrainz.
The button to run this script i missing now.
What can I do?

**Comment by atj** [comment]
No issues with the Discogs userscript here using Firefox and Violentmonkey. What browser and userscript extension are you using? Have you checked that the userscript is being run when you visit Discogs?

**Comment by zas** [comment]
Reported didn't answer to questions since months, closing.
