### ISSUE TITLE
Button does not show in Beatport

### ISSUE THREAD

**Issue by achmetinternet** [murdos/musicbrainz-userscripts#24]
Strange enough I must have the musicbrainz page in a tab open to the right of the beatport tab in order for the button to show. When I have the tab to the left, I need to move it to the right and reload the beatport page and the button will appear. I am using Firefox.

EDIT: have to correct myself, it just doesn't show once I searched something and clicked on the result. Only once I reload the same page.

**Comment by zas** [comment]
https://github.com/murdos/musicbrainz-userscripts/pull/76 should fix all issues
