### ISSUE TITLE
Bandcamp label backlink format has changed

### ISSUE THREAD

**Issue by johnlawsharrison** [murdos/musicbrainz-userscripts#241]
The bandcamp import script references a `span` tag with class "back-to-label-name" to retrieve the label name here: https://github.com/murdos/musicbrainz-userscripts/blob/master/bandcamp_importer.user.js#L194

It appears this tag is no longer used on the Bandcamp site, instead the label name shows up formatted like so:
(example)
```
<a href="http://subpop.bandcamp.com/artists?from=btl" class="back-to-label-link">
<span class="back-link-text">back to<br>Sub Pop</span>
</a>
```

It looks like this change was accounted for in other places:
eg https://github.com/murdos/musicbrainz-userscripts/blob/master/bandcamp_importer.user.js#L300

Since the label name/mbid is overwritten using mblinks.resolveMBID (https://github.com/murdos/musicbrainz-userscripts/blob/master/bandcamp_importer.user.js#L299) it seems like this will only cause an issue when importing releases from labels on Bandcamp that don't already exist in MusicBrainz.

**Comment by johnlawsharrison** [comment]
Haven't had an opportunity to test what happens with a label that isn't known to MusicBrainz (hard to find one off the top of my head)

**Comment by zas** [comment]
It should be fixed by https://github.com/murdos/musicbrainz-userscripts/pull/242
