### ISSUE TITLE
Beatport Localizes Release Metadata

### ISSUE THREAD

**Issue by VxJasonxV** [murdos/musicbrainz-userscripts#25]
Currently, the Beatport script looks for specific `<td>` elements that contain the text 'Release Date', 'Catalog #', and 'Label', and then uses adjacent `<td>` selectors to get the values that correspond to those keys. This doesn't work in non-English versions of the site, as those values are localized:

![screen shot 2014-10-14 at 01 03 23](https://cloud.githubusercontent.com/assets/1882/4625046/38b8fa4c-5370-11e4-8e67-410adb3d21a0.png)

(English, German, French, Spanish, Italian, Portuguese, Japanese)

The order seems to be consistent, so this aspect of the script should be dumbed down and done positionally instead.

**Comment by zas** [comment]
I can only get Beatport Pro in english, even though my preferred language is set to french.
I checked the Beatport Pro code for this, and it is the same thing, no way to extract data easily if text changes with languages.
We can use position of elements but it isn't very reliable either, or we could just build a list of text for each language...
