### ISSUE TITLE
Bandcamp importer breaks the purchase process

### ISSUE THREAD

**Issue by VxJasonxV** [murdos/musicbrainz-userscripts#26]
With the Bandcamp MBz Importer script active, trying to buy an album or a track fails. Clicking on the buy button emits the following in the console:

> Uncaught TypeError: Cannot read property 'cfg' of undefined

Something in the script is reacting poorly with Bandcamp's popover purchase dialog.

**Comment by pankkake** [comment]
I had it with Chrome too, so I only enabled it in Firefox

**Comment by pankkake** [comment]
An update this week or so finally fixed it for me. I think this can be closed if no one else is seeing the issue.
