### ISSUE TITLE
Discogs script does not work for Chrome, working version attached

### ISSUE THREAD

**Issue by Xrampino** [murdos/musicbrainz-userscripts#28]
Maybe we can do a thing so it will work with all browsers ? Here is what I did

https://gist.github.com/Xrampino/776da89853d61e355d4b

Basically I removed the fallback to Greasemonkey JS, changed the ajax request to a straightforward JSON, and changed `var discogsRelease = data.data;` to `var discogsRelease = data;`

Now it does work, but maybe it won't work anymore for Firefox, I haven't tested

**Comment by murdos** [comment]
Change committed.
