### ISSUE TITLE
Discogs: handle tracks in case of sub-tracks

### ISSUE THREAD

**Issue by pixel** [murdos/musicbrainz-userscripts#31]
In case of sub-tracks (eg: http://api.discogs.com/releases/5880212), current code ignores discogs tracks.

I will propose a pull request which takes the first sub-track "position" and makes things work nicely
(except that sub-tracks are not imported to musicbrainz, but musicbrainz does not handle it?)

cu

**Comment by murdos** [comment]
I wasn't aware that Discogs has introduced [index tracks/subtrack and headings](http://www.discogs.com/help/submission-guidelines-release-trk.html#Index_Tracks_And_Headings) and that the API was exposing a "*type_*" property.

This is definitely something that should be used by this script.

**Comment by awesomer** [comment]
I believe this is the same issue with this release?

http://www.discogs.com/Undertone-Sexy-Thing/release/1009184

If not, let me know and I will file on the other issue. :smile:

**Comment by zas** [comment]
@awesomer : it isn't exactly the same issue, because the release you linked has no sub-tracks (it is an "heading" + extra tracks)

**Comment by mll0** [comment]
(sorry, i'm not used to github and hopefully I'm doing what i intend)
I'd like to reopen this : importing https://www.discogs.com/release/9536040 created this kind of merge it seems (see https://musicbrainz.org/edit/61344391)
