### ISSUE TITLE
Juno Download: not here!

### ISSUE THREAD

**Issue by CatQuest** [murdos/musicbrainz-userscripts#33]
and it definitely should be. I have an ancient version (https://pastee.org/ya9x2) this is really old, and needs updating, for example to add the url in the "add link" box.
Further, it does VA release pretty badly - each track is entered with trackname [some title - some artist] and the trackartist as [album artist], so this will have to be edited some before inclusion here.

**Comment by pankkake** [comment]
Junodownload is a very big store and usually provides accurate label and catalog numbers.

**Comment by zas** [comment]
Importer added in https://github.com/murdos/musicbrainz-userscripts/commit/470f3322a7e1c8c63600c3a77c0806ed81b77f04
