### ISSUE TITLE
VGMdb importer presents Amazon links as purchase for relationships instead of AISN relationship

### ISSUE THREAD

**Issue by CyberSkull** [murdos/musicbrainz-userscripts#375]
The VGMdb importer presents Amazon links as one of the purchase for relationships instead of AISN relationship.

**Comment by augustjanse** [comment]
Could you provide an example VGMdb release?

**Comment by CyberSkull** [comment]
Try importing https://vgmdb.net/album/111671, you will see the amazon link flagged as the wrong relationship type.
