### ISSUE TITLE
Import Deezer releases into MusicBrainz

### ISSUE THREAD

**Issue by AllamC11** [murdos/musicbrainz-userscripts#396]
The script does not work correctly

- the import button does not appear in most of the cases.
- The text inside the button overflows.

**Comment by xhocquet** [comment]
For me, disabling my adblock/privacy addons helped the button appear more consistently. It still overflows but at least it's usable.

**Comment by Uatschitchun** [comment]
Script isn't working anymore here, too. 
Using it with Opera and it always needed a reload of the album page to appear, but now it doesn't show up anymore!

Tried with Firefox and got same result. 

I don't know how to debug with Opera or Firefox, can't find logs although I upped the loglevel!?

**Comment by matteron** [comment]
Figured out a a more permanent fix, will try to submit a pr shortly, but in the script if you change line 143 from
```JavaScript
$('div.toolbar-wrapper-full').append(mbUI);
```
to
```JavaScript
$('[data-testid="toolbar"]').append(mbUI);
```

It seems to work fine.  Though the styling a bit off now.

I don't love having to use this data attribute to query for the element, but it seems like they're running the class names through a pre-processor so they're nonsense.

**Comment by Kirstens-Curiousities** [comment]
Deezer button not showing again

**Comment by matteron** [comment]
The pr isn't in yet, so if you're using the script directly from this repo, you'll need to modify it with the [code above](https://github.com/murdos/musicbrainz-userscripts/issues/396#issuecomment-1097495558).
