### ISSUE TITLE
CD1D importer doesn't correctly handles releases with multiple mediums

### ISSUE THREAD

**Issue by murdos** [murdos/musicbrainz-userscripts#40]
No luck, the first release I found to test your script was http://cd1d.com/fr/album/chantent-mano-solo that has 2CDs but the script tries to import it as one big medium ;-)

**Comment by zas** [comment]
I would say luck instead ;)
I didn't do any test with multiples CD releases, CD1D is a bit a mess when it comes to extract data, the website structure (if any) is awful.
I'll provide a fix soon.

**Comment by zas** [comment]
Fixed in 3bc5a63e5fa3f2dc81f4f9871212e0c1eed23dab
