### ISSUE TITLE
Need help using VGMdb -> MB script

### ISSUE THREAD

**Issue by mitsufune** [murdos/musicbrainz-userscripts#402]
There isn't any documentation I can refer to and I can't seem to find any import button on the page:
![image](https://user-images.githubusercontent.com/85979326/125075697-8c44ee80-e0f1-11eb-95a7-6817ee12b405.png)

**Comment by augustjanse** [comment]
Hi, I wrote that script. If all goes well, a button should appear in the top right:

![image](https://user-images.githubusercontent.com/6920177/125175017-b964d000-e1c9-11eb-859f-1b84e938c2aa.png)

If it doesn't appear, try reloading the page. If it still doesn't appear, make sure you have installed the script in your userscript manager. In my screenshot you can see the Tampermonkey extension, also in the top right, with a 1 in red indicating that one userscript is loaded on this page.

**Comment by mitsufune** [comment]
Thanks! Apparently the script doesn't work in Greasemonkey for some reason. It works just as expected on Tampermonkey.
