### ISSUE TITLE
VGMdb Importer stopped working

### ISSUE THREAD

**Issue by Roshri** [murdos/musicbrainz-userscripts#404]
Up until last night the imported worked flawlessly but when I tried using it today, the import isn't showing on any release 
![image](https://user-images.githubusercontent.com/29184137/126222156-13658179-846f-4771-a051-eb262781ea99.png)
Tried reinstalling the script and changing from Tampermonkey to Violentmonkey but it isn't working on neither.
Also tried switching from Vivaldi browser to Firefox, still not working

**Comment by Roshri** [comment]
Nevermind it fixed itself

**Comment by Roshri** [comment]
Reopening because the odd behavior occurred again. I could import stuff until one hour ago and then it suddenly stopped working again.
Upon inspecting the console I got this error while loading the script.

```
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseApi (userscript.html?name=Import%20VGMdb%20releases%20into%20MusicBrainz.user.js&id=ff2edd61-9cde-4240-b967-96c43d9da7bc:584)
    at Function.onload (userscript.html?name=Import%20VGMdb%20releases%20into%20MusicBrainz.user.js&id=ff2edd61-9cde-4240-b967-96c43d9da7bc:577)
    at <anonymous>:4:80
    at Function.r.onload (eval at exec_fn (12714:2), <anonymous>:57:470)
    at <anonymous>:4:80
    at eval (eval at exec_fn (12714:2), <anonymous>:28:360)
    at <anonymous>:4:80
    at i (eval at exec_fn (12714:2), <anonymous>:5:165)
    at eval (eval at exec_fn (12714:2), <anonymous>:5:292)
```

Tried reinstalling the script and throws the same exception. Tested in Vivaldi using Tampermonkey

**Comment by augustjanse** [comment]
@Roshri, I downloaded a fresh version of Vivaldi but couldn't reproduce.

![image](https://user-images.githubusercontent.com/6920177/129778057-c2fcda44-3888-4a69-a145-7333b740457d.png)

It looks like this error would occur if the server at vgmdb.info had a problem, or if there were a problem with the connection caused by your end. Has it happened to you again recently? I don't think it has anything to do with the browser.

**Comment by Tenome** [comment]
I've encountered the following in the console on a fresh install on Firefox (seems to be about line "for (const commercial of websites['Commercial'])":

> Uncaught TypeError: 
> websites.Commercial is undefined
>     mapUrls moz-extension://5c8e096f-6af8-4e22-8cde-f9f317f95d86/userscripts/Import VGMdb releases into MusicBrainz.user.js?id=387a430c-ab3c-405e-890d-f13bc107ee0e:695
>     parseApi moz-extension://5c8e096f-6af8-4e22-8cde-f9f317f95d86/userscripts/Import VGMdb releases into MusicBrainz.user.js?id=387a430c-ab3c-405e-890d-f13bc107ee0e:599
>     onload moz-extension://5c8e096f-6af8-4e22-8cde-f9f317f95d86/userscripts/Import VGMdb releases into MusicBrainz.user.js?id=387a430c-ab3c-405e-890d-f13bc107ee0e:580
>     s eval:4
>     onload eval line 2 > Function:57
>     s eval:4
>     i eval line 2 > Function:28
>     s eval:4
>     i eval line 2 > Function:5
>     s eval line 2 > Function:5
>     v eval:13
>     v eval:13
>     s eval:4
>     t eval:12
>     s eval:4
>     h eval:12
>     h eval:12
>     send eval:13
>     s eval line 2 > Function:5
>     setTimeout eval line 2 > Function:6
>     i eval line 2 > Function:28
>     xmlhttpRequest eval line 2 > Function:35
>     message eval line 2 > Function:11
>     s eval:4
>     t eval:3
>     message eval line 2 > Function:11
>     message eval line 2 > Function:11
>     anonymous eval line 2 > Function:70
>     v eval:13
> eval line 4 > eval:695:34

**Comment by augustjanse** [comment]
@Tenome: Cool, I'll take a look at it, unless you want to have a go yourself? If not, please link a VGMdb release where you're having this problem.

**Comment by Tenome** [comment]
> @Tenome: Cool, I'll take a look at it, unless you want to have a go yourself? If not, please link a VGMdb release where you're having this problem.

Here's one.
https://vgmdb.net/album/18893

Commercial releases such as this one work fine.
https://vgmdb.net/album/113979

**Comment by augustjanse** [comment]
Please try the fix! I wrote a very short explanation in the pull request, makes sense that this would happen on some doujin releases.

**Comment by Tenome** [comment]
Seems to take about 15 seconds to load, but it appears to be working now. Thanks!

**Comment by augustjanse** [comment]
Yeah, that's probably the API. Thanks for using the script!

**Comment by augustjanse** [comment]
@Roshri I stumbled upon your problem. It does indeed look like it came from vgmdb.info having a server problem. You could print a warning or something, I guess, but I probably won't.
