### ISSUE TITLE
CD1D importer: Digital media with both FLAC and MP3 generates duplicated tracklist

### ISSUE THREAD

**Issue by murdos** [murdos/musicbrainz-userscripts#41]
While testing http://cd1d.com/fr/album/hurlements-en-scene I've noticed tracklist was added twice in the same medium. I guess this is because of MP3/FLAC, but I'm not sure

**Comment by zas** [comment]
Fixed in 3bc5a63e5fa3f2dc81f4f9871212e0c1eed23dab
