### ISSUE TITLE
Remove/reduce/update jQuery?

### ISSUE THREAD

**Issue by Schweinepriester** [murdos/musicbrainz-userscripts#468]
Hello there!

First up, thanks for your work here! :)

Before I attempt to send a PR I wanted to gauge your stance on removing jQuery, reducing the dependence and updating jQuery?
For example lib/mbimportstyle.js appears to use jQuery and in bandcamp_importer_helper.user.js I should be able to easily remove it. 
In bandcamp_importer.user.js usage could be reduced and jQuery updated, e.g. to the latest 2.x or even 3.

What do you say, should I attempt a PR? 0:-)

Disclosure: This issue is similar to https://github.com/ROpdebee/mb-userscripts/issues/425

**Comment by murdos** [comment]
@Schweinepriester : sure, please go ahead and submit a PR :+1:
