### ISSUE TITLE
Discogs - new layout for the "master" page of a release breaks displaying the MusicBrainz icon for the different releases

### ISSUE THREAD

**Issue by vzell** [murdos/musicbrainz-userscripts#501]
Discogs has switched to a new layout for the "master" page of a release which breaks displaying the MusicBrainz icon for the different releases ... see for example https://www.discogs.com/master/1101870-Bruce-Springsteen-Happy-New-Year-Live-At-Nassau-Coliseum-NY-12311980

**Comment by kellnerd** [comment]
Should have been fixed by #546
