### ISSUE TITLE
VGMdb link viewer no longer shows

### ISSUE THREAD

**Issue by cam1170** [murdos/musicbrainz-userscripts#513]
When I go to a release group like https://musicbrainz.org/release-group/3a55876d-0a14-4f1c-a85a-3f81f6268cea the vgmdb release links no longer show up. I'm not sure if other link types are affected.

**Comment by cam1170** [comment]
Let me correct myself, sometimes when the page load if show everything, sometimes it does not show the jesus2099 icon or the super mind control turbo stuff or this script's links but keeps this script's custom "Relationships" column. Maybe this issue is invalid and it's server issues?

**Comment by HibiscusKazeneko** [comment]
What script manager are you running?
There's a known issue with Violentmonkey's latest release breaking the injection method of various userscripts. This might be related to that.

**Comment by cam1170** [comment]
I'm using Violentmonkey 2.13.5 on Firefox, I didn't know about those issues, so I guess I'll close this. Thanks!
