### ISSUE TITLE
Catalog Number "None"

### ISSUE THREAD

**Issue by ItsME6969** [murdos/musicbrainz-userscripts#521]
Lots of releases on Discogs have `None` as the catalog number with the intention of stating that there is no catalog number for that release. So I think it would be nice if the discogs to musicbrainz script could check if catalog_no == "none", and just remove it.

**Comment by liftarn** [comment]
Why should we remove information? That it don't have a catalog number is also information. That way you know and don't have to go look for something that isn't there.

**Comment by ItsME6969** [comment]
Ok. I see where you're coming from but **technically** `None` is `Not` the catalog number. Somebody using Music Brainz API to tag their collection or whatever might still have to get rid of that somehow. But anyway I see your point I'll just go ahead and close then.

**Comment by atj** [comment]
Just to confirm what was discussed here, the userscript is correctly converting "none" to "[none]", which is the convention on MusicBrainz:

https://github.com/murdos/musicbrainz-userscripts/blob/b1da6eb48c45b2b0b09c506f00c7560ea62e7f4c/discogs_importer.user.js#L532-L536

https://musicbrainz.org/doc/Style/Release#Catalog_number

> If the release has no catalog number, use "[none]".

An empty catalogue number on MB means "there might be one but I don't know what it is".
