### ISSUE TITLE
Beatport import broken (site updated)

### ISSUE THREAD

**Issue by ruben966** [murdos/musicbrainz-userscripts#539]
Hi, the import button for beatport releases doesn't appear anymore.
Also noticed the beatport site layout looks different now. 

So the import script probably needs to be updated for it to work.

Added a before and after screenshots to show the site looks different now.
Before update:
![before update](https://github.com/murdos/musicbrainz-userscripts/assets/74718120/a50d909f-9a21-417c-953a-27fe433feba7)
After update:
![after update](https://github.com/murdos/musicbrainz-userscripts/assets/74718120/7f2fa677-0519-44a0-a1df-168747e45c08)

**Comment by kellnerd** [comment]
There's already a patch in #538 but it is currently marked as draft.

**Comment by kellnerd** [comment]
Should be working again with the patch from #538, except for releases with more than 100 tracks, see #540.
