### ISSUE TITLE
Idea: Last.fm import script

### ISSUE THREAD

**Issue by liftarn** [murdos/musicbrainz-userscripts#57]
Many independent artists (especially outside Europe and USA) use Last.fm to release their music so it would be nice to have a script to import them.
Last.fm uses release info from MusicBrainz so perhaps some kind of check to avoid roundtrips may be needed.

**Comment by zas** [comment]
Do last.fm has "releases" by itself ? all i can find are redirected to third-party shops.

**Comment by pankkake** [comment]
example: http://www.last.fm/music/Government+Alpha/FSCD12+-+GOVERNMENT+ALPHA+-+Groove+Test+Frequency+(2000)

Not to be confused to all the "releases" populated by crappy tags!

**Comment by liftarn** [comment]
Compare for instance http://www.last.fm/music/LukHash/Digital+Memories that is a Last.fm release with http://www.last.fm/music/Birmingham+6/Mindhallucination that is imported from MusicBrainz. Notice that releases created by artists or labels have a release label while the imported don't.

**Comment by zas** [comment]
https://github.com/murdos/musicbrainz-userscripts/pull/58

**Comment by zas** [comment]
Merged ;)
