### ISSUE TITLE
No more import button on discogs page

### ISSUE THREAD

**Issue by naregcenty** [murdos/musicbrainz-userscripts#583]
Import button not showing at discogs pages anymore. Noticed this behavior around the third week of October 2024.

**Comment by tbouska** [comment]
Check https://github.com/murdos/musicbrainz-userscripts/issues/579#issuecomment-2419633896.

If you open https://github.com/murdos/musicbrainz-userscripts/raw/4c56c16a05953845dda9d7df9ac650c728329718/discogs_importer.user.js then Tampermonkey will offer updating the script. Then Discogs starts working again.

This is just a workaround for those who can't wait ;)
