### ISSUE TITLE
"Import Discogs releases to Musicbraniz" script is no longer working properly for me. 

### ISSUE THREAD

**Issue by tigerman325** [murdos/musicbrainz-userscripts#593]
It's no longer has an import to Musicbrainz button on the page or any of the cool shortcuts to Musicbrainz for artist, releases, labels, etc.

**Comment by tigerman325** [comment]
NVM, I uninstalled it and reinstalled it and even though it had same version number, it works now.

**Comment by kellnerd** [comment]
Tampermonkey? See #579
