### ISSUE TITLE
Possibility to add the disc titles and release date for albums

### ISSUE THREAD

**Issue by Rouzax** [murdos/musicbrainz-userscripts#6]
I also posted this on http://userscripts.org/topics/126546 but I'm not sure that is monitored.
First of all many thanks for this wonderful script it saves heaps of time and frustration.

Would it be possible to add the disc titles and release date for albums?

For instance this release, http://www.discogs.com/release/3979680 has a title for the different CD's 
CD1 = Bar: Mixed By Nathan Cozzetto 
CD2 = Club: Mixed By Dan Van 
CD3 = After Party: Mixed By Carl Hanaghan 
You have to copy those by yourself 
http://musicbrainz.org/release/628d2a34-6e7d-4d...

Also the Release event Date is not populated, would that be possible?

**Comment by zas** [comment]
Disc titles are now supported, and release date was since a long time. Issue fixed.
