### ISSUE TITLE
Bandcamp URL not found on MB

### ISSUE THREAD

**Issue by pankkake** [murdos/musicbrainz-userscripts#60]
When going on https://sunn-live.bandcamp.com/album/sunn-o-20020809-blackbird-portland-or-usa the script can't find the release on MB, which should be https://musicbrainz.org/release/059d436c-4016-4b48-8190-215130a97cb3

MusicBrainz normalizes some URLs, like Bandcamp's, to have http instead of https, so this could be why it doesn't work in this case.

**Comment by zas** [comment]
It does for me, using latest script version
![capture du 2015-06-17 11 11 52](https://cloud.githubusercontent.com/assets/151042/8203395/c86e0d66-14e1-11e5-83af-f97b44b88d8a.png)

**Comment by pankkake** [comment]
Actually it's completely broken, I have "Uncaught TypeError: MBReleaseImportHelper.buildSearchButton is not a function" and no Import on MB button anymore
I suppose it's #59

**Comment by zas** [comment]
Was the script automatically updated ? or is this a manual upgrade ?
How did you solve the issue (if you did) ?

**Comment by pankkake** [comment]
Still not fixed after forced update and browser restart

**Comment by pankkake** [comment]
Uninstalled/reinstalled and it works now

**Comment by zas** [comment]
Weird, did you upgrade from an old version ?

**Comment by pankkake** [comment]
It was showing 2015.06.16something and now I have 2015.06.17.0

**Comment by zas** [comment]
Under Firefox + Greasemonkey ? or ?

**Comment by pankkake** [comment]
Chrome + Tampermonkey
I also have Firefox + Greasemonkey and it updated correctly! :)

**Comment by zas** [comment]
I think this is a tampermonkey issue, please have an eye on that for future upgrades.
We use multiple files for scripts (@require in header), and a relative link to lib files, it should work with tampermonkey as it does with greasemonkey.
