### ISSUE TITLE
Discogs:  feat. in Extra Track Info adds feat./& for every artist that follows.

### ISSUE THREAD

**Issue by killdabob** [murdos/musicbrainz-userscripts#64]
I admit this is a fringe case, but if feat./ft./whatever-variation is included in the Extra Track Information on Discogs, it will add Feat. or & for every artist that follows that track.
http://www.discogs.com/Various-Double-Dance-Promo-Music-Service-July-2005/release/6810869
is the release in question, track 7 is what breaks the script (with Ft. in the ETI).  Tracks 7-11 contained " Feat. " as the join phrase; tracks 12, 13 were correctly parsed; tracks 14, 15 had " & " as the join phrase; track 16 parsed correctly.  Notice that " Feat. " is titlecase on these incorrectly parsed tracks.  In all cases of incorrect Feat. or &, the join phrase was populated but a second artist line was not added.

**Comment by zas** [comment]
Please check if https://github.com/murdos/musicbrainz-userscripts/pull/65 fixes it for you.

**Comment by killdabob** [comment]
That seems to have done the trick.  Thanks for the quick turnaround on this one.

**Comment by zas** [comment]
Merged : 2bff7ff1929fe551ed224148f24e643bc6ce608f
