### ISSUE TITLE
Discogs import does not properly understand "Single Sided"

### ISSUE THREAD

**Issue by pankkake** [murdos/musicbrainz-userscripts#66]
It creates a Single type release.
It has always been there as far as I remember.

Example: http://www.discogs.com/release/1155254

**Comment by murdos** [comment]
The reason is we check if format description *contains* the word Single.
We can easily fix that by replacing the contains match by an *exact* match.
I just wonder if there are cases where a partial match could still be necessary.

**Comment by pankkake** [comment]
Or you can just exclude Single Sided, I have never seen another misleading string containing Single.
