### ISSUE TITLE
Discogs: Don't set medium title if there's only one medium

### ISSUE THREAD

**Issue by murdos** [murdos/musicbrainz-userscripts#69]
When you try to import e.g. http://www.discogs.com/release/827124 the script set the medium title, but it should not.

**Comment by zas** [comment]
Though there are cases where we should set the medium title even if there's only one.
Not sure how to "fix" this, since medium titles are just a guess from discogs "headings", they don't provide a true "medium title" field.

**Comment by murdos** [comment]
There's a reason the MB user interface doesn't allow you to set the medium title when there's only one medium. We should enforce this rule in the importer script.

**Comment by zas** [comment]
> There's a reason the MB user interface doesn't allow you to set the medium title when there's only one medium. 

I didn't think about that ;)

> We should enforce this rule in the importer script.

Then it is simple enough, if there is one medium and it has a title, remove it.

**Comment by pankkake** [comment]
The "best" way would be to set it considering all the sides, i.e. joining them with a / like it's done in https://musicbrainz.org/release/aab6300e-9465-4daa-b23a-ddb2bdc02831

Currently only the first title is taken.

**Comment by zas** [comment]
https://github.com/murdos/musicbrainz-userscripts/pull/70 merged
