### ISSUE TITLE
BeatPort Pro importer works only for english version

### ISSUE THREAD

**Issue by zas** [murdos/musicbrainz-userscripts#71]
https://pro.beatport.com/release/more-over/912753

Try english vs french.

Reason: matches based on content ie. "Release" or "Release Date"

**Comment by VxJasonxV** [comment]
#25 

While the screenshots indicate the classic interface, clearly the reasoning/details haven't changed under Pro.

**Comment by zas** [comment]
Not sure what it the best solution, thx to BeatPort shitty html.
Using position of elements looks very unreliable, so i will go to the far-from-perfect-but-it-works-tm way, that is keep the code as it is, but matches more languages.
Currently, we use 4 localized strings, and BeatPort Pro supports 6 languages, not a big deal.

**Comment by zas** [comment]
https://github.com/murdos/musicbrainz-userscripts/pull/75
