### ISSUE TITLE
Bandcamp: detect label by root URL

### ISSUE THREAD

**Issue by pankkake** [murdos/musicbrainz-userscripts#72]
Example: http://northernelectronics.bandcamp.com/album/june

The label https://musicbrainz.org/label/f6c14f30-a9a4-4bb1-8e57-5200ca081436 has http://northernelectronics.bandcamp.com/ associated.

**Comment by zas** [comment]
Good idea, i'll try to implement it.

**Comment by zas** [comment]
@pankkake : give a try to https://github.com/murdos/musicbrainz-userscripts/pull/74

It has the same limitation than artist mbid, that is we query asynchronously, and cache, and only on the next run we are able to use the cached mbid. This is something we need to improve, but it requires to change a lot of things. Apart this limitation it should work.

**Comment by pankkake** [comment]
Great, tested & it works!

> only on the next run we are able to use the cached mbid

Oh that explains some things.

**Comment by zas** [comment]
> Oh that explains some things.

We proceed like this:
- identify potential artist/release/rg/label/place urls
- for each url found, query MB web service for the specified type
- if found, the info is cached, and the MB link/icon is eventually displayed on the page

This is done asynchronously as we don't want to wait the full round of queries (a discogs page may have hundreds, and web service requires a delay between queries, so it may be a slow process, Bandcamp importer does few queries so it is faster).

The release data is extracted synchronously, when the document is loaded.

So at best, we can check the existing data from the cache (we store queries results in localStorage).
When the Import button appears, we may not have yet mbids we need, a workaround is : 
- load the page you want to import
- wait a bit the queries for entities are done (icons should appear when found, for artist/release/label/etc)
- reload the page
- import

For the Bandcamp importer, we could wait for the result of queries, as there are few, before displaying Import button, but i don't think it is great to have to wait full page loading + few seconds to be able to Import. I don't think the current behavior is much an issue when you are aware of it.

**Comment by zas** [comment]
https://github.com/murdos/musicbrainz-userscripts/pull/74 merged
