### ISSUE TITLE
Track length issues

### ISSUE THREAD

**Issue by V-Toll** [murdos/musicbrainz-userscripts#73]
Hey!

I think the "Import Bandcamp releases to MusicBrainz" script (don't know if the others have it, too) has an issue with the track length of imported songs. Every time I import a release to MusicBrainz, some of the songs have an extra second. Here is an example:

Release: http://audioantihero.bandcamp.com/album/five-long-years

Bandcamp:
![1](https://cloud.githubusercontent.com/assets/7504584/8613049/8dd0864c-26da-11e5-88c4-464b110bf788.png)

MusicBrainz:
![2](https://cloud.githubusercontent.com/assets/7504584/8613053/925b8e32-26da-11e5-9ccb-55dd9a2d7af2.png)

See the difference between the track lengths? That happens all the time (but not with all of the tracks)...

Bandcamp:
![3](https://cloud.githubusercontent.com/assets/7504584/8613109/61c6fe90-26db-11e5-9832-0b376b546f18.png)

MusicBrainz:
![4](https://cloud.githubusercontent.com/assets/7504584/8613111/6392b732-26db-11e5-99b1-fdae7dcd365d.png)

So, any idea what's going on here?

**Comment by VxJasonxV** [comment]
The Bandcamp API provides times in milliseconds. It's a difference in rounding by MusicBrainz I think. IIRC the Bandcamp script just passes the milliseconds through.

**Comment by pankkake** [comment]
Yes, I've seen it before: in the end, we have the times that are closer to the files.

**Comment by zas** [comment]
Yes, displayed durations (on Bandcamp or MusicBrainz) are rounded, but the Bandcamp script uses millisecond-precision durations provided by Bandcamp, and MusicBrainz stores milliseconds too.

For the given example, track 2 has a duration (provided by Bandcamp) of 150.583 seconds, which is 2 minutes 30 seconds and 583 milliseconds, rounded to nearest integer = 2:31, rounded down = 2:30

So this isn't a bug.
