### ISSUE TITLE
Qobuz: API request returns 404 error

### ISSUE THREAD

**Issue by augustjanse** [murdos/musicbrainz-userscripts#78]
The [Ajax request](https://github.com/murdos/musicbrainz-userscripts/blob/125afdd65167009ede5f9a233ec190d47ea9c6d6/qobuz_importer.user.js#L145-L158) fails for all releases I've tried, [this one](http://www.qobuz.com/fr-fr/album/shit-va-pin-de-vet-du/0060253713769) for example. The [wsUrl variable](http://www.qobuz.com/api.json/0.2/album/get?album_id=0060253713769&app_id=667867760) shows the following when opened in a browser, which should explain the failures.

    {"status":"error","code":404,"message":"No result matching given argument"}

So, something up with the API probably?

Version: 2015.07.16.1
Greasemonkey: 3.2

**Comment by zas** [comment]
Interesting, the same release works for me.
Can you check with firebug (or the like) which url is called by the page itself ?
Something like http://www.qobuz.com/api.json/0.2/album/get?album_id=0060253713769&app_id=667867760

**Comment by augustjanse** [comment]
I'm not sure what you're asking me to do. I extracted the link passed to the request by simply adding a `console.log(wsUrl)` to the script. It is the exact same one you linked, and has the content that's in the first comment.

I tried the script on the computer beside me with Firefox and Chrome just to make sure, didn't work either. Could try using a different connection later. I'm in Sweden, where Qobuz isn't officially available, if that matters.

Trying [other](https://github.com/Qobuz/api-documentation/tree/master/endpoints/album) services, the example requests for [Album Service : getFeatured](http://www.qobuz.com/api.json/0.2/album/getFeatured?app_id=100000000&type=new-releases&genre_id=64&limit=2) and [Album Service : search]( http://www.qobuz.com/api.json/0.2/album/search?app_id=100000000&query=John%20Cage&limit=2) work fine, but [Album Service : get](http://www.qobuz.com/api.json/0.2/album/get?app_id=1000000000&album_id=0886443927087) doesn't. No idea why this one has decided not to.

**Comment by augustjanse** [comment]
Found this: https://github.com/Qobuz/api-documentation/issues/18

Looks like my IP is detected as Swedish, which causes these errors even though I can view the album page in my browser. I guess this means I can't use this script, maybe add a comment about the issue somewhere?
