### ISSUE TITLE
I think I found a bug with "Import Discogs releases to MusicBrainz" userscript

### ISSUE THREAD

**Issue by AzoresOne** [murdos/musicbrainz-userscripts#79]
Every time I import a release into MBz from Discogs (using the script), at the final page (Recordings Tab), when asked to add new recording the tab/sub-page takes forever to load or never loads.

**Comment by pankkake** [comment]
It sometimes happens to me and I have to paste the first recording or visit the "duplicates" tab for the others to show. In any case for me it's a MB server bug

**Comment by murdos** [comment]
I confirm that this is a MB bug, since most of the times importing from Discogs works fine regarding the recordings tab.
