### ISSUE TITLE
Idea: VGMdb import script

### ISSUE THREAD

**Issue by augustjanse** [murdos/musicbrainz-userscripts#81]
[VGMdb](http://vgmdb.net/) is a high quality data source that I personally import releases manually from a lot. Would love to see a import script if there's time, thanks!

**Comment by murdos** [comment]
For reference, there's no official API. 
However there's an unofficial but maintained API provided by http://vgmdb.info/ that provides information in different formats (including JSON).

**Comment by liftarn** [comment]
VGMDB handles multiple artist releases quite differently than MusicBrainz so they may be a bit tricky.

**Comment by zas** [comment]
VGMDB lists performers, but does it provide them per track somewhere ? API seems to list them for the whole album
I'm not familiar with this site, how does it list Various Artists or Unknown artists ?
Also it lists tracks in english and japanese, is there a way to know which one appears on the release itself ?
Example: http://vgmdb.info/album/1279?format=json
Also, it seems to me most albums there should follow classical style (performers / composers / lyricists), what do you think ?

**Comment by zas** [comment]
@murdos : VGMDB provides a lot of cover art, can we import them somehow ? Related to https://github.com/murdos/musicbrainz-userscripts/issues/50

**Comment by augustjanse** [comment]
Soundtracks ("Classification: Original Soundtrack" on VGMdb) should follow [Style/Specific types of releases/Soundtrack](https://wiki.musicbrainz.org/Style/Specific_types_of_releases/Soundtrack). A fair amount of the releases aren't soundtracks and should follow ordinary style.

I think track artists are only in the Notes section if there's more than one, so that would have to be manual. Might be a problem to find release artist in some cases as well.

It would probably be safe to assume that if a track has a Japanese tracklist, that's the one that appears on the release.

**Comment by murdos** [comment]
@zas: Cover art upload (#50) is kind of a nightmare because of CORS, that's why I've not yet achieved a Discogs uploader script. 
The solution I found involves cross-origin communication using Window.postMessage() but I've not found the energy to work on it again. I'll try to make as generic as possible to reuse it on other sites.

**Comment by CyberSkull** [comment]
I'm not so sure about having a VGMdb importer, but I would love to see a userscript to see if a VGMdb entity has a matching MusicBrainz entity.

**Comment by fxthomas** [comment]
I created a small script to import data into the "Add Release" form just like the "Add Release" Picard plugin does : https://gist.github.com/fxthomas/fd85e906e41f4e6e06f38e92a497005b.

After using it you still need to clean up the data, but at least the tracklist is there and mostly complete, which is what usually takes time when adding albums manually!

**Comment by VxJasonxV** [comment]
The Track Parser on MBz’ site has been perfectly suitable to me for seeding the structured data that VGMdb does provide.
