### ISSUE TITLE
MusicBrainz UI Enhancements

### ISSUE THREAD

**Issue by rdgarfinkel** [murdos/musicbrainz-userscripts#84]
If you didn't know already, seems like MusicBrainz made an update to the site which makes the UI Enhancements break, at least in the editing area of the site. For example, you can't move forward with the editing ability with UI Enhancements active. Disabling UI Enhancements allows for editing to work.

**Comment by murdos** [comment]
I haven't encountered any problem recently.
Please be more specific: what browser are you using, and what exactly doesn't work (you can provide links if it's easier).

**Comment by rdgarfinkel** [comment]
For example, here: http://musicbrainz.org/release/b5dcddce-f1a5-4d99-96b9-5487aeb0142c/edit.
Using Google Chrome (44.0.2403.155) with Tampermonkey (3.11).

With MusicBrainz UI Enhancer
![edit1](https://cloud.githubusercontent.com/assets/7954223/9519041/7419e5d4-4c89-11e5-9e45-d242957aaab8.PNG)

Without MusicBrainz UI Enhancer
![edit2](https://cloud.githubusercontent.com/assets/7954223/9519048/824edc72-4c89-11e5-86ee-ef6fe2e61a6d.PNG)

**Comment by murdos** [comment]
I've (finally!) been able to reproduce the issue, I'll probably release a fix today.
