### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by Xrampino** [murdos/musicbrainz-userscripts#86]
Could you change the namespace from userscripts.org to github for easier lookup ?

**Comment by zas** [comment]
Yes, i thought about it for old scripts still using userscripts.org namespace. But it has one drawback, it will break auto-update feature of already installed scripts, not sure it is worth.
What do you think guys?

**Comment by murdos** [comment]
I don't think it's worth too. 
Breaking auto-update feature would be more damaging than keeping an old namespace.

**Comment by Xrampino** [comment]
1/ I guess one day the switch has to be done anyway (userscripts.org is dead)
2/ I couldn't find the source of the script in my Greasemonkey dashboard, huge problem imo

**Comment by murdos** [comment]
1/ Well, a namespace is just a namespace, there's not problem if the URI doesn't exist anymore. It could stay forever, for historical reason.
2/ I don't know exactly what you mean by "Greasemonkey dashboard", but I have no problem at all with Firefox + Greasemonkey to see this userscript and access its source

**Comment by Xrampino** [comment]
https://theezitguy.files.wordpress.com/2015/01/tampermonkey_dashboard.jpg

Homepage leads to namespace (so there IS a problem for me, if not for you)

**Comment by murdos** [comment]
http://wiki.greasespot.net/Metadata_Block#.40namespace : Namespace is by no way supposed to be an homepage.
Tampermonkey (and not GreaseMonkey) seems to assume too much from the namespace value.
Won't fix.
