### ISSUE TITLE
discogs script moves ill-formated track on next medium

### ISSUE THREAD

**Issue by loujine** [murdos/musicbrainz-userscripts#89]
Although I don't use the script, I've seen the problem in https://musicbrainz.org/edit/35330537

Track "2-.23 	Le Carnaval" in discogs (note the incorrect ".") was apparently moved to CD 3 track 1 in https://musicbrainz.org/release/5d143526-f547-4dd6-ab06-cec6093ca0f6

**Comment by zas** [comment]
Confirmed.
It should be fixed by https://github.com/murdos/musicbrainz-userscripts/pull/91

**Comment by zas** [comment]
https://github.com/murdos/musicbrainz-userscripts/pull/91 merged
