### ISSUE TITLE
Discogs import script stopped working?

### ISSUE THREAD

**Issue by Rovastar** [murdos/musicbrainz-userscripts#90]
I have been using this for ages (a day or so ago the last time I just it) but stopped working today.

I did notice that yesterday (about 18 or so hours ago) discogs was down for maintenance for a while maybe they updated/changed something.....or is it just me?

**Comment by zas** [comment]
I just tested discogs import script, seems to work atm

**Comment by murdos** [comment]
The issue was on Discogs side: 
http://www.discogs.com/forum/thread/702451#7006458
http://www.discogs.com/forum/thread/702537

**Comment by Rovastar** [comment]
aha that explains it. Thanks.
