### ISSUE TITLE
discogs script: adding featured artists

### ISSUE THREAD

**Issue by Rovastar** [murdos/musicbrainz-userscripts#92]
For my sins the majority of stuff I add to Musicbrainz is electronic stuff this often contains "featured" artists.

It would be nice if the script could add these automatically. They clearly are labeled "Featuring - " 
where featuring can be " feat. " in MB.

I am sure you know what I mean but here is a typical example that I am adding at the moment.
http://www.discogs.com/Various-Shogun-Audio-Presents-2015/release/7735180

(edit: sometimes they are more complex and have featured, vocals, etc -"
http://www.discogs.com/Spectrasoul-The-Mistress/release/7208518)

**Comment by liftarn** [comment]
That is stuff that would go into relationships, not into track title or artist name.

**Comment by murdos** [comment]
liftarn is right, and I don't think the script should move artists used in relationships in Discogs to artist credits in MusicBrainz.

**Comment by Rovastar** [comment]
What are you on about?

This is clearly to be added track listing.

I do not know how much you about musicbrainz but here is the wiki page about using featured artists.
https://musicbrainz.org/doc/Style/Artist_Credits/Featured_artists


Here are my musicbrainz releases for the above releases. 

https://musicbrainz.org/release/9e9d1f12-ea6c-4749-b445-9ba2b8e74e98

https://musicbrainz.org/release/49046d09-41b4-4279-9287-9255a42e6af6

You are implying what I have done is wrong. I await the impending edit war then......

I suggest you read up about featured artists.

**Comment by liftarn** [comment]
The style guide says "they're given credit on the cover or track listing in a manner which elevates their contribution above normal liner note credits" and as they are in the liner notes on Discogs they should not be put in the artist field.

**Comment by Rovastar** [comment]
I await your edit war then sir. Of which you will lose. You truely do not understand musicbrainz at all.

**Comment by reosarevok** [comment]
For what it's worth, I've seen quite a few cases where the "featured" artist in discogs is not actually listed as feat. on the actual release. So it might be tricky to just assume that they're always good to put in the artist credit field. That said, "as they are in the liner notes on Discogs they should not be put in the artist field" is a bit of a strange argument - they deal with standardising feat. in one way, we do it in another, where they put them isn't representative of where they are in the original release tracklist and Discogs are clearly not the actual liner notes we should strive to follow :)

**Comment by Rovastar** [comment]
Well any import you should check it. If you are not that you are doing it wrong.
Also Discogs is a user generated database so *not* a perfect source so there will at times be mistakes there.

99% of the time the featured that are displayed are what we want in Musicbrainz.
TBH I don't think they deal with featured in a different way to Musicbrianz.....besides no-one contributing on this issue track ever enters releases with featured artists.
some only enter the low hanging fruit to Musicbrainz.....

**Comment by augustjanse** [comment]
@Rovastar, please calm down. You are being rude.

I do agree that Discogs usually enter artists in this way, that would be entered as artist credits in MusicBrainz. Compare for example [this release](http://www.discogs.com/Miley-Cyrus-Bangerz/release/4978820) to its scanned tracklist. I don't know of any release that uses the relation in another way. On [this release](http://www.discogs.com/Lars-Winnerb%C3%A4ck-Med-Solen-I-%C3%96gonen/release/945439) for example, guest vocals are indicated with a "Vocals" relation and not as "Featuring". So without further research, I would think the relation is equivalent to artist credits in MusicBrainz.

**Comment by liftarn** [comment]
The way Discogs deal with feat artists is like http://www.discogs.com/artist/153287-Coma-feat-LTG

**Comment by reosarevok** [comment]
Hmm... from their guidelines, definitely not the first, that seems like an error. "Never create or credit a collaborative artist in any credit field" (http://www.discogs.com/help/doc/submission-guidelines-release-artist#The_Join_Field_And_Artist_Collaboration). It does seem that the current idea is to do like we do and put them in the artist field, separated with a join phrase. That said, there are *tons* of these "featuring" ones as relationships too, so it seems like it would be reasonable to seed those as artists too. But it's not the end of the world either way :)

**Comment by liftarn** [comment]
An any case, it should not be done by default and in doubt you should check the liner notes.

**Comment by augustjanse** [comment]
Is there any reason not to do it by default? I think there would be as big a risk of mistakenly leaving them in when they're added by default as there would be of mistakenly forgetting to add them when they're not. Of course users should always double check their imports, but I see no reason not to have the script do this when there's risk of errors either way.

**Comment by liftarn** [comment]
You should not do it be default as the guidelines say you should not do it.

**Comment by Rovastar** [comment]
Whose guidelines are you talking about liftarn?
Musicbrainz? Discogs?

Your examples are in general not typical of how things are entered on discogs. In fact Musicbrianz has many more worse than that (in fact Musicbrainz in general is much worse (the dev refusal to add any type of warning to when (and nearly every new user does it) enters featured artist included wrong doesn't help either but that is another issue))
Have a look here:
http://musicbrainz.org/search?query=feat.&type=artist&method=indexed

but like I said they are both user generated databases so mistakes like this happen.

I apologize for my tone, the thing is the majority of releases I add to music have these featured artists for most tracks  and naturally presumed it was a an oversight not including it. And to instantly dismiss my query as in a tone of "you are doing it wrong you idiot" when I wasn't is going to annoy me.

The script currently is not that useful for me as I have to do a lot of manual entries where there could be very little.

**Comment by liftarn** [comment]
At https://musicbrainz.org/doc/Style/Artist_Credits/Featured_artists it says "they're given credit on the cover or track listing in a manner which elevates their contribution above normal liner note credits".

**Comment by Rovastar** [comment]
Well done for linking to a URL that I mentioned firs. Bravo.

I know how it works and Discogs and Musicbrianz should do the same thing. It looks like you understand little about either site.

**Comment by liftarn** [comment]
If the feat. artist only is in the liner notes they should not go into the artist field on MB. You seem to want to put them there no matter what.

**Comment by Rovastar** [comment]
You seem to want to leave them out no matter what.
It goes without saying that it is a featured artist on the cover it is likely in the linear notes.
Digital releases for example will not have linear notes your idea is to exclude all of these.
Like I say 99% of the time what is in Discogs is what we want. You obviously have no experience in entering these types of releases.

**Comment by reosarevok** [comment]
I haven't really seen any case in my life where there's an actual "feat." credit (as opposed to any other relationship-like credit) that is only listed on the liner notes and not on the actual tracklists. They might exist, but they sound pretty rare... I'm not sure why the insistence that they belong as relationships. I mean, of course they *also* belong as relationships, but :)

**Comment by liftarn** [comment]
Looking at http://www.discogs.com/help/doc/submission-guidelines-release-artist#The_Join_Field_And_Artist_Collaboration it seems Discogs also have proper feat artists in the artist field.

**Comment by zas** [comment]
I'm a bit late on this interesting discussion.

From what i know about discogs, "Featuring -" is used mostly when the artist is featuring on the track list (tiltle - artistA feat. artistB), but of course discogs doesn't have it always right.

Since it is easier to remove a featuring artist from artist credits than adding them afterwards, i would think it could be useful to parse this field, it would be right more often than wrong imho.

Import scripts are not meant to be perfect, but to help editors. Anyone importing data HAS to ensure imported data is correct.

So, while Rovastar is a bit harsh (and shouldn't), i think he is right on this, and tend to think having such feature (<...) would help more than not.

MB guidelines are pretty clear, but cover art and liner notes aren't always anyway. Plus label/artists often omit featuring artists on digital media (while they are present on the CD version e.g.)

I see no reason to not add them by default (once someone wrote the matching code....), as it seems to me they are far more often right than wrong.
Issues may arise more from incorrect artists listed in featuring field on discogs, but once again, editors are supposed to verify data.

**Comment by JuniorJPDJ** [comment]
I'm also suffering with having to add all featuring artists at myself. It would be much easier if I could just remove artists which shouldn't be here that if I have to add all the artists and double-check if I didn't forgot anyone.
