### ISSUE TITLE
Discogs import to MB only works on http?

### ISSUE THREAD

**Issue by Paxos-Map** [murdos/musicbrainz-userscripts#93]
Discogs from now on only works on https mode,  i try to remove the "s" from the https prefix so i can make the script work.  this was working till now, now Discogs redirects me back to https mode, so the script not working for me anymore, any solution pls?

**Comment by johtso** [comment]
Yeah, extension seems to be completely broken at the moment.

**Comment by zas** [comment]
Please try https://github.com/murdos/musicbrainz-userscripts/pull/94

**Comment by augustjanse** [comment]
2016.01.08.0 didn't work today, so I updated. Thanks!

**Comment by liftarn** [comment]
I can import using the updated script, but the icons for found artists/release groups/releases don't seem to update properly.

**Comment by johtso** [comment]
I think searching is now broken because we look up the `https` version of the discogs url in the musicbrainz api, but it doesn't match the `http` version in the database..

**Comment by johtso** [comment]
https://github.com/murdos/musicbrainz-userscripts/pull/95
