### ISSUE TITLE
Idea: FMA import script

### ISSUE THREAD

**Issue by stragu** [murdos/musicbrainz-userscripts#97]
Hi there!

I was wondering: how tricky would it be to make a script to import releases from the FMA website?
Examples or releases:
http://freemusicarchive.org/music/Various_Artists/Of_Men_And_Machines/
http://freemusicarchive.org/music/cloud_mouth/songs_from_the_sewer/
http://freemusicarchive.org/music/Podington_Bear/Springtime/
http://freemusicarchive.org/music/Broke_For_Free/Directionless_EP/

What could be parsed:
- release artist
- release title
- track titles
- track lenghts
- track artist (for both single artist and various artist releases)
- label
- license
- "download for free" link
- release date via "RELEASED" (not "UPLOADED"!)
- label via "LABEL"

Happy to work on it but I am completely new to Java so I would need some pointers...

**Comment by zas** [comment]
Using their API is the way to go if it provides all what we need : https://freemusicarchive.org/api

**Comment by stragu** [comment]
Great, that makes much more sense. Any idea which existing script would be the best to base it on?

**Comment by madmouser1** [comment]
Hi all, I would like to assist with this import script. @stragu any work done on it yet that you can share?

**Comment by stragu** [comment]
Hi madmouser1! Thank you for offering. I haven't started on anything, but I'd be very happy to assist in any way (with my limited capacity to code).

On April 22, 2016 8:27:51 PM AEST, madmouser1 <notifications@github.com> wrote:
>Hi all, I would like to assist with this import script. @stragu any
>work done on it yet that you can share?
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/murdos/musicbrainz-userscripts/issues/97#issuecomment-213370989

--
Stéphane Guillou
stragu.github.io

Sent from my Fairphone with K-9 Mail. Please excuse my brevity.

You can encrypt our communications by using OpenPGP. My public key
4E211060 is available on the keys.gnupg.net server.

**Comment by madmouser1** [comment]
@stragu I am a noob myself, let's see what we can do. I have created a fork & branch for FMA at https://github.com/madmouser1/musicbrainz-userscripts/tree/FMA .
You should be able to contribute to that repository.
Let's chat on IRC #metabrainz about the approach.

**Comment by madmouser1** [comment]
@zas  what is the best approach on userscripts with things like API KEY that FreeMusicArchive require, currently I hardcode it and assign it to a variable?

**Comment by zas** [comment]
> @zas what is the best approach on userscripts with things like API KEY that FreeMusicArchive require, currently I hardcode it and assign it to a variable?

Well, ideally this should be user configurable via UI, but at first just hardcode one, at the top of script, using an obvious variable name, and a comment explaining it.
FMA_API_KEY = "xxxx";

**Comment by madmouser1** [comment]
hi, pull request created : https://github.com/murdos/musicbrainz-userscripts/pull/111
I have added a UI > localStorage for API Key.

**Comment by madmouser1** [comment]
@stragu any comments or suggestions from your side?

**Comment by stragu** [comment]
Great work, @madmouser1 ! Thanks for doing everything. I have experimented with it and it has worked great so far. MusicBrainz is in read-only mode at the moment, so I couldn't experiment further, but I will come back here if anything comes up.

**Comment by zas** [comment]
Merged.

Thank you @madmouser1 !
