### ISSUE TITLE
Discogs: Track length wrong on double vinyl release

### ISSUE THREAD

**Issue by augustjanse** [murdos/musicbrainz-userscripts#98]
When importing [this release](https://www.discogs.com/Veronica-Maggio-Handen-I-Fickan-Fast-Jag-Bryr-Mig/release/5668028) all track lengths on the second medium are displaced one track up, with the bottom track length being left empty.

This bug occurs with the latest update, Greasemonkey, all other userscripts disabled.

**Comment by zas** [comment]
The last track (D3) has no duration.
From my tests, the tracklist is correctly imported.
D2 has 4:08 duration as expected.
I don't see any issue here.

**Comment by augustjanse** [comment]
Oh, that got me confused. No wonder the track lengths didn't match my rip. Thanks!

**Comment by zas** [comment]
Feel free to add the duration on MB though since you have the disc ;)
